sonar.projectKey=JongEunLee310_project_stock
sonar.organization=jongEunLee310
sonar.projectName=project_stock

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=alembic/**,**/__pycache__/**
